FROM python:3.9

COPY requirements.txt /opt/app/
RUN pip3 install -r /opt/app/requirements.txt

COPY converters /opt/app/converters
COPY schemas /opt/app/schemas
COPY topics.py /opt/app/
COPY streaming.py /opt/app/

WORKDIR /opt/app/
CMD ["python3", "streaming.py"]