version: '3.9'

services:

  exporter_blocks:
    build: ./
    restart: always
    deploy:
      mode: replicated
      replicas: 4
    environment:
      - KAFKA_GROUP_ID=exporter_archive_blocks
      - KAFKA_TOPICS=ton.public.blocks
      - CONVERTER=blocks
      - MAX_FILE_SIZE=100000000
      - PARTITION_MODE=adding_date
    env_file:
      - exporter.env
    logging:
      driver: local
      options:
        max-size: 10M

  exporter_transactions:
    build: ./
    restart: always
    deploy:
      mode: replicated
      replicas: 4
    environment:
      - KAFKA_GROUP_ID=exporter_archive_transactions
      - KAFKA_TOPICS=ton.public.transactions
      - CONVERTER=transactions
      - MAX_FILE_SIZE=100000000
      - PARTITION_MODE=adding_date
    env_file:
      - exporter.env
    logging:
      driver: local
      options:
        max-size: 10M

  exporter_messages:
    build: ./
    restart: always
    deploy:
      mode: replicated
      replicas: 4
    environment:
      - KAFKA_GROUP_ID=exporter_archive_messages
      - KAFKA_TOPICS=ton.public.messages
      - CONVERTER=messages
      - MAX_FILE_SIZE=100000000
      - PARTITION_MODE=adding_date
    env_file:
      - exporter.env
    logging:
      driver: local
      options:
        max-size: 10M

  exporter_messages_with_data:
    build: ./
    restart: always
    deploy:
      mode: replicated
      replicas: 4
    environment:
      - KAFKA_GROUP_ID=exporter_archive_messages_with_data
      - KAFKA_TOPICS=ton.public.messages
      - CONVERTER=messages_with_data
      - MAX_FILE_SIZE=100000000
      - PARTITION_MODE=adding_date
    env_file:
      - exporter.env
    logging:
      driver: local
      options:
        max-size: 10M

  exporter_account_states:
    build: ./
    restart: always
    deploy:
      mode: replicated
      replicas: 4
    environment:
      - KAFKA_GROUP_ID=exporter_account_states_3
      - KAFKA_TOPICS=ton.public.latest_account_states
      - CONVERTER=account_states
      - MAX_FILE_SIZE=200000000
      - PARTITION_MODE=adding_date
    env_file:
      - exporter.env
    logging:
      driver: local
      options:
        max-size: 10M

  exporter_jetton_events:
    build: ./
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - KAFKA_GROUP_ID=exporter_jetton_events
      - KAFKA_TOPICS=ton.parsed.jetton_mint,ton.public.jetton_burns,ton.public.jetton_transfers
      - CONVERTER=jetton_events
      - PARTITION_MODE=adding_date
    env_file:
      - exporter.env
    logging:
      driver: local
      options:
        max-size: 10M

  exporter_jetton_metadata:
    build: ./
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - KAFKA_GROUP_ID=exporter_jetton_metadata
      - KAFKA_TOPICS=ton.parsed.jetton_metadata
      - CONVERTER=jetton_metadata
      - PARTITION_MODE=adding_date
    env_file:
      - exporter.env
    logging:
      driver: local
      options:
        max-size: 10M

  exporter_nft_metadata:
    build: ./
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - KAFKA_GROUP_ID=exporter_nft_metadata
      - KAFKA_TOPICS=ton.parsed.nft_item_metadata,ton.parsed.nft_collection_metadata
      - CONVERTER=nft_metadata
      - PARTITION_MODE=adding_date
    env_file:
      - exporter.env
    logging:
      driver: local
      options:
        max-size: 10M
        
  exporter_dex_trades:
    build: ./
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - KAFKA_GROUP_ID=exporter_dex_trades
      - KAFKA_TOPICS=ton.parsed.dex_swap_parsed,ton.parsed.gaspump_trade,ton.parsed.tonfun_bcl_trade
      - CONVERTER=dex_trades
      - PARTITION_MODE=adding_date
    env_file:
      - exporter.env
    logging:
      driver: local
      options:
        max-size: 10M

  exporter_dex_pools:
    build: ./
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - KAFKA_GROUP_ID=exporter_dex_pools
      - KAFKA_TOPICS=ton.prices.dex_pool
      - CONVERTER=dex_pools
      - PARTITION_MODE=adding_date
    env_file:
      - exporter.env
    logging:
      driver: local
      options:
        max-size: 10M

  exporter_balances_history:
    build: ./
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - KAFKA_GROUP_ID=exporter_balances_history
      - KAFKA_TOPICS=ton.public.latest_account_states,ton.public.jetton_wallets
      - CONVERTER=balances_history
      - PARTITION_MODE=adding_date
    env_file:
      - exporter.env
    logging:
      driver: local
      options:
        max-size: 10M

  exporter_nft_items:
    build: ./
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - KAFKA_GROUP_ID=exporter_nft_items
      - KAFKA_TOPICS=ton.parsed.nft_items
      - CONVERTER=nft_items
      - PARTITION_MODE=adding_date
    env_file:
      - exporter.env
    logging:
      driver: local
      options:
        max-size: 10M

  exporter_nft_transfers:
    build: ./
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - KAFKA_GROUP_ID=exporter_nft_transfers
      - KAFKA_TOPICS=ton.public.nft_transfers
      - CONVERTER=nft_transfers
      - PARTITION_MODE=adding_date
    env_file:
      - exporter.env
    logging:
      driver: local
      options:
        max-size: 10M

  exporter_nft_sales:
    build: ./
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - KAFKA_GROUP_ID=exporter_nft_sales
      - KAFKA_TOPICS=ton.public.getgems_nft_sales,ton.public.getgems_nft_auctions
      - CONVERTER=nft_sales
      - PARTITION_MODE=adding_date
    env_file:
      - exporter.env
    logging:
      driver: local
      options:
        max-size: 10M

  streaming:
    build:
      context: ./
      dockerfile: Dockerfile.streaming
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - KAFKA_GROUP_ID=streaming
      - KAFKA_BROKER=cdc-using-debezium-kafka:29092
    logging:
      driver: local
      options:
        max-size: 10M

networks:
  default:
    name: database_default
    external: true