TOPIC_MESSAGES = "ton.public.messages"
TOPIC_BLOCKS = "ton.public.blocks"
TOPIC_TRANSACTIONS = "ton.public.transactions"
TOPIC_ACCOUNT_STATES = "ton.public.latest_account_states"
TOPIC_JETTON_WALLETS = "ton.public.jetton_wallets"
TOPIC_JETTON_TRANSFERS = "ton.public.jetton_transfers"
TOPIC_JETTON_BURN = "ton.public.jetton_burns"
TOPIC_JETTON_MINT = "ton.parsed.jetton_mint"
TOPIC_JETTON_METADATA = "ton.parsed.jetton_metadata"
TOPIC_NFT_ITEMS = "ton.parsed.nft_items"
TOPIC_NFT_TRANSFERS = "ton.public.nft_transfers"
TOPIC_NFT_SALES = "ton.public.getgems_nft_sales"
TOPIC_NFT_AUCTIONS = "ton.public.getgems_nft_auctions"
TOPIC_NFT_ITEMS_METADATA = "ton.parsed.nft_item_metadata"
TOPIC_NFT_COLLECTIONS_METADATA = "ton.parsed.nft_collection_metadata"

TOPIC_DEX_SWAPS = "ton.parsed.dex_swap_parsed"
TOPIC_GASPUMP_EVENTS = "ton.parsed.gaspump_trade"
TOPIC_TONFUN = "ton.parsed.tonfun_bcl_trade"

TOPIC_DEX_POOLS = "ton.prices.dex_pool"

